[package]
name = "projeto-bd"
description = "Projeto da disciplina de Banco de Dados"
version = "0.1.0"
authors = [ "Gabriel Fontes <g.fontes@usp.br>" ]
readme = "README.md"
edition = "2018"
license = "MIT"

[dependencies.rocket]
version = "0.5.0-rc.1"
[dependencies.rocket_db_pools]
version = "0.1.0-rc"
features = ["deadpool_postgres"]
[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]
[dependencies.sass-rocket-fairing]
version = "0.1"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.rust_decimal]
version = "1.17"
features = ["tokio-postgres"]

[dependencies.strum]
version = "0.22"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[patch.crates-io]
rocket = { git = "https://github.com/Misterio77/Rocket", branch = "context-namespace-result"}
rocket_db_pools = { git = "https://github.com/Misterio77/Rocket", branch = "context-namespace-result"}
rocket_dyn_templates = { git = "https://github.com/Misterio77/Rocket", branch = "context-namespace-result"}
sass-rocket-fairing = { git = "https://github.com/SyedAhkam/sass-rocket-fairing" }
